/**
 * Application artifacts: after every submitted application, save the user's
 * paper trail to disk — the exact resume sent, every answer given, the fill
 * report, a human-readable summary — plus refresh one master ledger.xlsx.
 *
 * Extensions may only write inside the browser's download directory, so
 * everything lands under Downloads/LarpMaxer/:
 *
 *   LarpMaxer/
 *     ledger.xlsx                          ← one row per application, always current
 *     2026-08-27_acme_data-analyst/
 *       application.md                     ← summary: role, link, what was sent
 *       answers.json                       ← every field, value, and its source
 *       fill-report.json                   ← what the page verified
 *       Jordan_CV.pdf                      ← the resume actually attached
 *
 * Failures here never fail the run — the application already went out.
 */

import type { ApplicationRecord } from "@larpmaxer/core";
import { buildLedgerXlsx, ledgerRowsFromRecords } from "@larpmaxer/core";
import { getRecords, getResumeBase64, getSettings } from "./storage.js";

/** Save the per-application folder and refresh the ledger. Never throws. */
export async function saveApplicationArtifacts(record: ApplicationRecord): Promise<void> {
  try {
    const { saveArtifacts } = await getSettings();
    if (saveArtifacts === false) return;
    const dir = `LarpMaxer/${folderSlug(record)}`;

    await download(`${dir}/application.md`, "text/markdown", textB64(summaryMd(record)));
    if (record.plan) {
      const answers = record.plan.answers.map((a) => ({
        field: a.fieldId,
        value: a.resume ? a.resume.filename : a.value,
        source: a.source,
      }));
      await download(`${dir}/answers.json`, "application/json", textB64(pretty(answers)));
    }
    if (record.report) {
      await download(`${dir}/fill-report.json`, "application/json", textB64(pretty(record.report)));
    }
    const resume = record.plan?.answers.find((a) => a.resume !== undefined)?.resume;
    if (resume) {
      const b64 = await getResumeBase64(resume.id);
      if (b64 !== undefined) {
        await download(`${dir}/${safeName(resume.filename)}`, safeMime(resume.mime), b64);
      }
    }
    await refreshLedger();
  } catch (err) {
    console.warn(`[larpmaxer] artifacts skipped: ${String(err)}`);
  }
}

/** Rebuild Downloads/LarpMaxer/ledger.xlsx from every stored record. */
export async function refreshLedger(): Promise<void> {
  const records = await getRecords();
  const submitted = records.filter((r) => r.submittedAt !== undefined || r.phase === "done");
  if (submitted.length === 0) return;
  const xlsx = buildLedgerXlsx(ledgerRowsFromRecords(submitted));
  await download(
    "LarpMaxer/ledger.xlsx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    bytesB64(xlsx),
    "overwrite",
  );
}

// ---------------------------------------------------------------------------

function folderSlug(record: ApplicationRecord): string {
  const date = (record.submittedAt ?? new Date().toISOString()).slice(0, 10);
  const name = [record.company, record.jobTitle].filter(Boolean).join(" ") || record.adapterId;
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return `${date}_${slug || "application"}`;
}

/** Reduce a filename to a safe basename: no separators, no traversal, no tricks. */
function safeName(filename: string): string {
  const base = filename.split(/[\/]/).pop() ?? "resume";
  const cleaned = base.replace(/[^A-Za-z0-9._-]/g, "_").replace(/^\.+/, "");
  return cleaned === "" ? "resume" : cleaned.slice(0, 100);
}

/** Allow only the MIME types a resume can legitimately carry. */
function safeMime(mime: string): string {
  const allowed = [
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "text/plain",
    "application/rtf",
  ];
  return allowed.includes(mime) ? mime : "application/octet-stream";
}

function summaryMd(record: ApplicationRecord): string {
  const lines = [
    `# ${record.jobTitle ?? "Application"}`,
    "",
    `- Company: ${record.company ?? "(not captured)"}`,
    `- Job posting: ${record.url}`,
    `- ATS: ${record.adapterId}`,
    `- Submitted: ${record.submittedAt ?? "(pending)"}`,
    `- Result: ${(record.submit?.evidence ?? []).join(" | ") || record.phase}`,
    "",
    "## What was sent",
    "",
    "| Field | Value | Source |",
    "|---|---|---|",
  ];
  const labels = new Map(record.report?.fields.map((f) => [f.fieldId, f.label]) ?? []);
  for (const a of record.plan?.answers ?? []) {
    const label = labels.get(a.fieldId) ?? a.fieldId;
    const value = a.resume ? a.resume.filename : String(a.value);
    lines.push(`| ${mdCell(label)} | ${mdCell(value)} | ${a.source} |`);
  }
  lines.push("", "Generated by LarpMaxer — everything above came from your own profile.");
  return lines.join("\n");
}

const mdCell = (s: string): string => s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

const pretty = (v: unknown): string => JSON.stringify(v, null, 2);

/** UTF-8 → base64 without Buffer (service-worker safe, chunked for large input). */
function textB64(text: string): string {
  return bytesB64(new TextEncoder().encode(text));
}

function bytesB64(bytes: Uint8Array): string {
  const CHUNK = 0x8000;
  let bin = "";
  for (let i = 0; i < bytes.length; i += CHUNK) {
    bin += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(bin);
}

/** One chrome.downloads call; data: URLs sidestep MV3's missing createObjectURL. */
async function download(
  filename: string,
  mime: string,
  b64: string,
  conflictAction: "uniquify" | "overwrite" = "uniquify",
): Promise<void> {
  await chrome.downloads.download({
    url: `data:${mime};base64,${b64}`,
    filename,
    // @types/chrome models this as an enum; the runtime API takes the string.
    conflictAction: conflictAction as chrome.downloads.FilenameConflictAction,
    saveAs: false,
  });
}
